### ISSUE TITLE
Build Failed?

### ISSUE THREAD

**Issue by oenama** [a2/arex-7#19]
Users/User/arex-7/arex-7/ArexKit/Models/Medication+Scheduling.swift:1:8: error: no such module 'Pistachio'
import Pistachio
       ^

*\* BUILD FAILED **

The following build commands failed:
    CompileSwift normal arm64 /Users/User/arex-7/arex-7/ArexKit/Models/Medication+Scheduling.swift
    CompileSwift normal arm64 /Users/User/arex-7/arex-7/ArexKit/Functions/ReactiveCocoaAdditions.swift
    CompileSwift normal arm64 /Users/User/arex-7/arex-7/ArexKit/Models/Time.swift
    CompileSwift normal arm64 /Users/User/arex-7/arex-7/ArexKit/View Models/MedicationDetailViewModel.swift
    CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(5 failures)

Frameworks are not found!?

**Comment by a2** [comment]
You need to run `carthage bootstrap` in the project's root directory, as stated in the [README](https://github.com/a2/arex-7/blob/24fe5b009119c3c0d49d6152af2002fa9acdde33/README.md).
