### ISSUE TITLE
Should use CocoaPods

### ISSUE THREAD

**Issue by neonichu** [a2/arex-7#4]

**Comment by segiddins** [comment]
@neonichu should send in a PR instead of making issues :stuck_out_tongue_winking_eye:

**Comment by a2** [comment]
I wanted to use CocoaPods but I wasn't sure how to get [ReactiveCocoa](ReactiveCocoa/ReactiveCocoa's)'s _swift-1.2_ branch to work with it?

**Comment by neonichu** [comment]
We should figure that out - @ashfurrow might already know.

**Comment by endocrimes** [comment]
@a2 `pod "ReactiveCocoa", "3.0.0-alpha.1"`

**Comment by a2** [comment]
@DanielTomlinson I have to install CocoaPods on my new laptop. Hold on :stuck_out_tongue_winking_eye:

**Comment by a2** [comment]
@DanielTomlinson Yeah it looks like [they're on par now](https://github.com/ReactiveCocoa/ReactiveCocoa/compare/3.0.0-alpha.1...swift-1.2). I'll update all that now :smile:

**Comment by neonichu** [comment]
🎉
